# -*- coding: utf-8 -*-
nameField = "sk01"

utf8dict  = {
  "sk01":"Name",
  "sk02":"Fuerza",
  "sk03":"Constitución",
  "sk04":"Destreza", 
  "sk05":"Inteligencia",
  "sk06":"Sabiduría",
  "sk07":"Carisma",
  "sk08":"Acrobacias",
  "sk09":"Aguante",
  "sk10":"Arcanos",
  "sk11":"Atletismo",
  "sk12":"Diplomacia",
  "sk13":"Dungeons",
  "sk14":"Engañar",
  "sk15":"Historia",
  "sk16":"Hurto",
  "sk17":"Intimidar",
  "sk18":"Naturaleza",
  "sk19":"Percepción",
  "sk20":"Perspicacia",
  "sk21":"Recursos",
  "sk22":"Religión",
  "sk23":"Sanar",
  "sk24":"Sigilo",
  }

skillList = ["sk01",
             "sk02",
             "sk03",
             "sk04",
             "sk05",
             "sk06",
             "sk07",
             "sk08",
             "sk09",
             "sk10",
             "sk11",
             "sk12",
             "sk13",
             "sk14",
             "sk15",
             "sk16",
             "sk17",
             "sk18",
             "sk19",
             "sk20",
             "sk21",
             "sk22",
             "sk23",
             "sk24"]
